### ISSUE TITLE
trying to install on Frappe Cloud

### ISSUE THREAD

**Issue by hussainabuhajjaj** [aakvatech/PropMS#33]
Trying to install on frappe cloud and its keep showing this error on the last step 

bench get-app propms
Getting PropMS
$ git clone file:///home/frappe/context/apps/propms  --depth 1 --origin upstream
Cloning into 'propms'...
Ignoring dependencies of file:///home/frappe/context/apps/propms. To install dependencies use --resolve-deps
Installing propms
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/propms
ERROR: Could not find a version that satisfies the requirement erpnext (from propms) (from versions: none)
ERROR: No matching distribution found for erpnext
ERROR:
Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/frappe/.local/lib/python3.7/site-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/home/frappe/.local/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/frappe/.local/lib/python3.7/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/.local/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.7/site-packages/bench/commands/make.py", line 166, in get_app
    resolve_deps=resolve_deps,
  File "/home/frappe/.local/lib/python3.7/site-packages/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/frappe/.local/lib/python3.7/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.7/site-packages/bench/app.py", line 249, in install
    resolution=self.local_resolution,
  File "/home/frappe/.local/lib/python3.7/site-packages/bench/app.py", line 574, in install_app
    f"{bench.python} -m pip install {quiet_flag} --upgrade -e {app_path} {cache_flag}"
  File "/home/frappe/.local/lib/python3.7/site-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/home/frappe/.local/lib/python3.7/site-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError
INFO: A newer version of bench is available: 5.15.2 → 5.17.2
executor failed running [/bin/sh -c bench get-app file:///home/frappe/context/apps/propms `#stage-apps-propms`]: exit code: 1
> [stage-0 25/27] RUN --mount=type=cache,target=/home/frappe/.cache,uid=1000,gid=1000 --mount=type=bind,source=apps/propms,target=/home/frappe/context/apps/propms bench get-app file:///home/frappe/context/apps/propms `#stage-apps-propms`:
executor failed running [/bin/sh -c bench get-app file:///home/frappe/context/apps/propms `#stage-apps-propms`]: exit code: 1

please help me to resolve this

**Comment by YefriTavarez** [comment]
Remove the line that says `erpnext` from the file /home/frappe/frappe-bench/apps/propms/requirements.txt

**Comment by hussainabuhajjaj** [comment]
how to remove it am using frappe and installing it directly from there !! please guide me thru it

**Comment by YefriTavarez** [comment]
Use ChatGPT for the details, brother.
